sudo: false
install: true
language: node_js
node_js: 
    - "8"
env:
    - TEST_SUITE=short-tests
    - TEST_SUITE=long-tests
    - TEST_SUITE=lint
script:
    make -j2 ${TEST_SUITE}

jobs:
    include:
        - stage: deploy
          env: TEST_SUITE=dist
